# Generated by Django 4.0.4 on 2022-04-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=50, null=True)),
                ('clientAddress', models.CharField(blank=True, max_length=70, null=True)),
                ('clientGSTIN', models.CharField(blank=True, max_length=17, null=True)),
                ('clientPAN', models.CharField(blank=True, max_length=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField(blank=True, null=True)),
                ('cost_per_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('ONLINE', 'ONLINE'), ('CHEQUE', 'CHEQUE')], default='CASH', max_length=100)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PAID', max_length=100)),
                ('cgst', models.CharField(blank=True, max_length=20, null=True)),
                ('sgst', models.CharField(blank=True, max_length=20, null=True)),
                ('gross_amount', models.IntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=40, null=True)),
                ('account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=40, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=15, null=True)),
                ('cin', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_gstin', models.CharField(blank=True, max_length=30, null=True)),
                ('arn', models.CharField(blank=True, max_length=30, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecblicapp.clientdetail')),
            ],
        ),
        migrations.CreateModel(
            name='clientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecblicapp.clientdetail')),
            ],
        ),
    ]
