# Generated by Django 4.0.4 on 2022-04-29 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0002_bankdetails_remove_invoice_account_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_info', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecblicapp.bankdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='bank_detail',
        ),
    ]
