# Generated by Django 4.0.4 on 2022-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0003_bank_delete_bank_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='kindAttn',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='sacCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
