# Generated by Django 4.0.4 on 2022-04-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0004_clientdetail_kindattn_clientdetail_saccode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetail',
            name='kindAttn',
        ),
        migrations.RemoveField(
            model_name='clientdetail',
            name='sacCode',
        ),
    ]
