# Generated by Django 4.0.4 on 2022-05-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0005_remove_clientdetail_kindattn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='clientEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
