# Generated by Django 4.0.4 on 2022-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0007_invoice_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='send_email',
            field=models.CharField(blank=True, choices=[('only_generate', 'only_generate'), ('generate_and_send', 'generate_and_send')], max_length=20, null=True),
        ),
    ]
