# Generated by Django 4.0.4 on 2022-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0008_alter_invoice_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='kindAttn',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='send_email',
            field=models.CharField(blank=True, choices=[('only_generate', 'Only Generate'), ('generate_and_send', 'Generate And Send Mail')], default='only_generate', max_length=20, null=True),
        ),
    ]
