# Generated by Django 4.0.4 on 2022-05-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0012_remove_invoice_id_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.AutoField(default=500, primary_key=True, serialize=False),
        ),
    ]
