# Generated by Django 4.0.4 on 2022-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0013_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='gst_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.CharField(blank=True, max_length=20, null=True)),
                ('sgst', models.CharField(blank=True, max_length=20, null=True)),
                ('gross_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sgst',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.IntegerField(default=500, primary_key=True, serialize=False),
        ),
    ]
