# Generated by Django 4.0.4 on 2022-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0014_gst_details_remove_invoice_cgst_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gst_details',
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
