# Generated by Django 4.0.4 on 2022-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0015_delete_gst_details_invoice_cgst_invoice_gross_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gst_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_cgst', models.CharField(blank=True, max_length=20, null=True)),
                ('d_sgst', models.CharField(blank=True, max_length=20, null=True)),
                ('d_gross_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
