# Generated by Django 4.0.4 on 2022-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0016_gst_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='cin',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='supplier_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='supplier_pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='swift_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='clientGSTIN',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='clientPAN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
