# Generated by Django 4.0.4 on 2022-05-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0017_alter_bankdetails_cin_alter_bankdetails_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency_type',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=5, null=True),
        ),
    ]
