# Generated by Django 4.0.4 on 2022-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0018_invoice_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.AutoField(default=500, primary_key=True, serialize=False),
        ),
    ]
