# Generated by Django 4.0.4 on 2022-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0028_alter_payment_ps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ps',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PENDING', max_length=10, null=True),
        ),
    ]
