# Generated by Django 4.0.4 on 2022-05-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0032_alter_invoice_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency_type',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR')], default='INR', max_length=5),
        ),
    ]
