# Generated by Django 4.0.4 on 2022-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0033_alter_invoice_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cost_per_unit',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
