# Generated by Django 4.0.4 on 2022-05-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0036_alter_invoice_cost_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
