# Generated by Django 4.0.4 on 2022-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0041_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNumber',
            fields=[
                ('number', models.IntegerField(default=5000, primary_key=True, serialize=False)),
            ],
        ),
    ]
