# Generated by Django 4.0.4 on 2022-05-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0042_autonumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
