# Generated by Django 4.0.4 on 2022-05-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0043_alter_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
