# Generated by Django 4.0.4 on 2022-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0048_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qty_type',
            field=models.CharField(choices=[('HRS', 'HRS'), ('DAY', 'DAY')], default='HRS', max_length=3),
        ),
        migrations.AlterField(
            model_name='autonumber',
            name='number',
            field=models.IntegerField(default=100001, primary_key=True, serialize=False),
        ),
    ]
