# Generated by Django 4.0.4 on 2022-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0049_invoice_qty_type_alter_autonumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='qty_type',
            field=models.CharField(choices=[('NONE', 'NONE'), ('HRS', 'HRS'), ('DAY', 'DAY')], default='HRS', max_length=5),
        ),
    ]
