# Generated by Django 4.0.4 on 2022-05-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0050_alter_invoice_qty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='t_2',
            field=models.TextField(default='2) This Bill is payable by Electronic transfer/ DD/ Cheque in favor of Tecblic Private Limited. For payment made by electronic fund transfer, please send details to accounts@tecblic.com (Invoice number, Invoice amount, Tecblic Bank name and Account number, Payment date, Amount paid, TDS if applicable). Queries can be sent to us at accounts@tecblic.com.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='t_3',
            field=models.TextField(default='3) Please make payment within 7 days of receipt of this invoice.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='t_4',
            field=models.TextField(default='4) TDS certificate, if applicable, should be issued in favor of Tecblic Private Limited, AAHCT7338J of the Billing Entity and emailed to accounts@tecblic.com or couriered to above address.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='t_5',
            field=models.TextField(default='5) We declare that invoice shows the actual price of goods/services described and that all particulars are correct.'),
        ),
    ]
