# Generated by Django 4.0.4 on 2022-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0051_invoice_t_2_invoice_t_3_invoice_t_4_invoice_t_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='home/tecblic/finance/receivables')),
            ],
        ),
    ]
