# Generated by Django 4.0.4 on 2022-05-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0052_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
