# Generated by Django 4.0.4 on 2022-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0053_delete_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='savePdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
