# Generated by Django 4.0.4 on 2022-05-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0055_alter_savepdf_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='savePdf',
        ),
    ]
