# Generated by Django 4.0.4 on 2022-05-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0056_delete_savepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecblicapp.bankdetails'),
        ),
    ]
