# Generated by Django 4.0.4 on 2022-05-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0057_invoice_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_type',
            field=models.CharField(choices=[('IMPORT', 'IMPORT'), ('EXPORT', 'EXPORT')], default='IMPORT', max_length=6),
        ),
    ]
