# Generated by Django 4.0.4 on 2022-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0058_invoice_gst_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='uniqueId',
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='clientAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_type',
            field=models.CharField(choices=[('DOMESTIC', 'DOMESTIC'), ('EXPORT', 'EXPORT')], default='DOMESTIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qty_type',
            field=models.CharField(choices=[("No's", "No's"), ('HRS', 'HRS'), ('DAY', 'DAY')], default='HRS', max_length=5),
        ),
    ]
