# Generated by Django 4.1.5 on 2023-01-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0062_alter_invoice_gst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('----', '----'), ('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque'), ('Swift Transfer', 'Swift Transfer')], default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PAID', max_length=100),
        ),
        migrations.CreateModel(
            name='InvoiceDesription',
            fields=[
                ('description_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecblicapp.invoice')),
            ],
        ),
    ]
