# Generated by Django 4.1.5 on 2023-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecblicapp', '0064_remove_invoice_cost_per_unit1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='activeClient',
            field=models.BooleanField(default=True, verbose_name='Active Client'),
        ),
    ]
